[font]
normal = { family = "Iosevka NF", style = "Regular" }
bold = { family = "Iosevka NF", style = "Bold" }
italic = { family = "Iosevka NF", style = "Italic" }
bold_italic = { family = "Iosevka NF", style = "Bold Italic" }
size = 12.0

[colors.primary]
background = "#0b0f14"
foreground = "#c8ccd4"

[colors.cursor]
cursor = "#c8ccd4"
text = "#2a2e36"

[colors.normal]
black = "#0b0f14"
red = "#d75f5f"
green = "#5f875f"
yellow = "#af875f"
blue = "#5f87af"
magenta = "#875f87"
cyan = "#5f9ea0"
white = "#c0c0c0"

[colors.bright]
black = "#3a3f4b"
red = "#ff6c6b"
green = "#98be65"
yellow = "#ecbe7b"
blue = "#51afef"
magenta = "#c678dd"
cyan = "#46d9ff"
white = "#ffffff"
