[font]
normal = { family = "Iosevka NF", style = "Regular" }
bold = { family = "Iosevka NF", style = "Bold" }
italic = { family = "Iosevka NF", style = "Italic" }
bold_italic = { family = "Iosevka NF", style = "Bold Italic" }
size = 12.0

[general]
import = [
  "~/.config/alacritty/solarized_light.toml"
]

